spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: validate
        show_sql: false
        format_sql: false
        use_sql_comments: false
        jdbc.batch_size: 5000
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: mbprojecttest794@gmail.com  #https://www.baeldung.com/spring-email
    password: jpdx ujmt uzus rlpe #https://support.google.com/mail/answer/7104828?hl=en&rd=3&visit_id=638195765566773400-3814427644
    properties:
      mail:
        smtp:
          debug: true
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  datasource:
    url: jdbc:postgresql://localhost:5432/mbbusiness
    username: postgres
    password: Mzoi2bV1%
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          my-client:
            authorization-grant-type: client_credentials
            client-id: mbprojectclient
            client-secret: u7bs3CiLtuYVXvUDYJ6Pu8MHL6j372yR
        provider:
          my-client:
            token-uri: http://localhost:8080/realms/mb_project/protocol/openid-connect/token
  web:
    locale-resolver: accept_header
keycloak:
  realm: mb_project
  auth-server-url: http://localhost:8080
  ssl-required: none
  resource: mbprojectclient
  user_url: /admin/realms/%s/users
  token_url: /realms/%s/protocol/openid-connect/token
  authorization_url: /realms/%s/protocol/openid-connect/certs
  user_locked_url: /admin/realms/%s/attack-detection/brute-force/users/
  credentials:
    secret: u7bs3CiLtuYVXvUDYJ6Pu8MHL6j372yR
    use-resource-role-mappings: true
    bearer-only: true

user:
  temporal:
    owner: 0 * * * * *
    other: 0 0 1 * * ?

sms:
  url: http://isms.center/api/sms/send
  username: mbproject
  password: 1E7Fx3hXN
  originator: KiT_Notify
  otpschedule: 0 */30 * * * *

springdoc:
  enable-spring-security: true


