server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  web:
    locale-resolver: accept_header
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: validate
        show_sql: false
        format_sql: false
        use_sql_comments: false
        jdbc.batch_size: 5000
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
 version: 2.1.0
 paths-to-exclude: