version: "3.8"

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    container_name: postgres
    image: library/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mzoi2bV1%
      POSTGRES_DB: postgres
    ports:
      - "5444:5432"
    networks:
      - keycloak_net


networks:
  keycloak_net:
    driver: bridge